In [21]:
# CELL 1: Locate the available TIRTL Traffic Count files

from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Main folder where the downloaded datasets are stored
base_folder = Path(
    r"C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After"
)

# Find all folders containing TIRTL data
tirtl_folders = sorted([
    folder
    for folder in base_folder.iterdir()
    if folder.is_dir() and "tirtl" in folder.name.lower()
])

print("=" * 70)
print("TIRTL DATA FOLDERS")
print("=" * 70)

print("\nNumber of TIRTL folders found:", len(tirtl_folders))

for folder in tirtl_folders:
    print("-", folder.name)


# Search all TIRTL folders for CSV files
tirtl_files = []

for folder in tirtl_folders:
    tirtl_files.extend(folder.rglob("*.csv"))

tirtl_files = sorted(tirtl_files)


print("\n" + "=" * 70)
print("TIRTL CSV FILES")
print("=" * 70)

print("\nTotal CSV files found:", len(tirtl_files))

print("\nFirst 10 CSV files:")

for file in tirtl_files[:10]:
    print(file)

print("\nLast 5 CSV files:")

for file in tirtl_files[-5:]:
    print(file)

======================================================================
TIRTL DATA FOLDERS
======================================================================

Number of TIRTL folders found: 8
- tirtl_15min_volume_classification_april_2026
- tirtl_15min_volume_classification_august_2026 (1)
- tirtl_15min_volume_classification_february_2026
- tirtl_15min_volume_classification_january_2026
- tirtl_15min_volume_classification_july_2026
- tirtl_15min_volume_classification_june_2026
- tirtl_15min_volume_classification_march_2026
- tirtl_15min_volume_classification_may_2026

======================================================================
TIRTL CSV FILES
======================================================================

Total CSV files found: 215

First 10 CSV files:
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_april_2026\TIRTLDATA_20260401.csv
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_april_2026\TIRTLDATA_20260402.csv
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_april_2026\TIRTLDATA_20260403.csv
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_april_2026\TIRTLDATA_20260404.csv
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_april_2026\TIRTLDATA_20260405.csv
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_april_2026\TIRTLDATA_20260406.csv
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_april_2026\TIRTLDATA_20260407.csv
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_april_2026\TIRTLDATA_20260408.csv
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_april_2026\TIRTLDATA_20260409.csv
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_april_2026\TIRTLDATA_20260410.csv

Last 5 CSV files:
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_may_2026\TIRTLDATA_20260527.csv
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_may_2026\TIRTLDATA_20260528.csv
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_may_2026\TIRTLDATA_20260529.csv
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_may_2026\TIRTLDATA_20260530.csv
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_may_2026\TIRTLDATA_20260531.csv

In [23]:
# CELL 2: Inspect the structure of one TIRTL Traffic Count file

# Select the first available CSV file
sample_file = tirtl_files[0]

print("=" * 70)
print("SAMPLE TIRTL FILE")
print("=" * 70)

print("\nFile being inspected:")
print(sample_file)


# Read one daily file
sample_tirtl = pd.read_csv(
    sample_file,
    low_memory=False
)


# Dataset dimensions
print("\nDATASET SIZE")

print("Rows:", f"{len(sample_tirtl):,}")
print("Columns:", len(sample_tirtl.columns))


# Column names
print("\nCOLUMN NAMES")

for number, column in enumerate(
    sample_tirtl.columns,
    start=1
):
    print(f"{number}. {column}")


# Preview the data
print("\nFIRST 5 ROWS")

display(sample_tirtl.head())


# Data types
print("\nDATA TYPES")

print(sample_tirtl.dtypes)


# Missing values
print("\nMISSING VALUES IN SAMPLE FILE")

missing_sample = pd.DataFrame({
    "Column": sample_tirtl.columns,
    "Missing_Values": sample_tirtl.isna().sum().values,
    "Missing_Percentage": (
        sample_tirtl.isna().sum().values /
        len(sample_tirtl) * 100
    ).round(4)
})

display(missing_sample)


# Show unique values for columns with a small number of categories
print("\nCATEGORICAL COLUMN CHECK")

for column in sample_tirtl.columns:
    
    unique_count = sample_tirtl[column].nunique(dropna=True)
    
    if unique_count <= 20:
        print(f"\n{column} ({unique_count} unique values):")
        print(sample_tirtl[column].dropna().unique())

======================================================================
SAMPLE TIRTL FILE
======================================================================

File being inspected:
C:\Users\LENOVO\Desktop\Project Urban\Data\Raw\After\tirtl_15min_volume_classification_april_2026\TIRTLDATA_20260401.csv

DATASET SIZE
Rows: 1,160,005
Columns: 7

COLUMN NAMES
1. date
2. time_bin
3. site
4. heading
5. vehicle_class
6. speed_bin
7. volume

FIRST 5 ROWS

,date,time_bin,site,heading,vehicle_class,speed_bin,volume
0,2026-04-01,0:00,2,W,10,70km/hr to < 75km/hr,1
1,2026-04-01,0:00,2,W,11,70km/hr to < 75km/hr,1
2,2026-04-01,0:00,2,W,9,75km/hr to < 80km/hr,1
3,2026-04-01,0:00,2,W,1,80km/hr to < 85km/hr,1
4,2026-04-01,0:00,2,W,3,80km/hr to < 85km/hr,1

DATA TYPES
date             object
time_bin         object
site              int64
heading          object
vehicle_class     int64
speed_bin        object
volume            int64
dtype: object

MISSING VALUES IN SAMPLE FILE

          Column  Missing_Values  Missing_Percentage
0           date               0                 0.0
1       time_bin               0                 0.0
2           site               0                 0.0
3        heading               0                 0.0
4  vehicle_class               0                 0.0
5      speed_bin               0                 0.0
6         volume               0                 0.0

CATEGORICAL COLUMN CHECK

date (1 unique values):
['2026-04-01']

heading (4 unique values):
['W' 'E' 'N' 'S']

vehicle_class (15 unique values):
[10 11  9  1  3  2  5  8  0  4  6  7 13 14 12]

In [25]:
# CELL 3: Check file structure, coverage and basic traffic information

from collections import Counter

file_information = []

all_sites = set()
all_vehicle_classes = set()
all_headings = set()
all_speed_bins = set()

date_records = Counter()

total_rows = 0
total_volume = 0

earliest_date = None
latest_date = None

different_structures = set()

expected_columns = [
    "date",
    "time_bin",
    "site",
    "heading",
    "vehicle_class",
    "speed_bin",
    "volume"
]


for number, file in enumerate(tirtl_files, start=1):

    print(
        f"Processing file {number}/{len(tirtl_files)}:",
        file.name
    )

    file_rows = 0
    file_dates = set()

    # Read each large daily file in smaller pieces
    for chunk in pd.read_csv(
        file,
        chunksize=200_000,
        low_memory=False
    ):

        file_rows += len(chunk)
        total_rows += len(chunk)

        # Record the column structure
        different_structures.add(
            tuple(chunk.columns)
        )

        # Convert date safely
        dates = pd.to_datetime(
            chunk["date"],
            errors="coerce"
        )

        valid_dates = dates.dropna()

        if not valid_dates.empty:

            chunk_min = valid_dates.min()
            chunk_max = valid_dates.max()

            if earliest_date is None or chunk_min < earliest_date:
                earliest_date = chunk_min

            if latest_date is None or chunk_max > latest_date:
                latest_date = chunk_max

            file_dates.update(
                valid_dates.dt.date.unique()
            )

            date_counts = (
                valid_dates.dt.date.value_counts()
            )

            for date_value, count_value in date_counts.items():
                date_records[date_value] += int(count_value)

        # Collect unique site IDs
        all_sites.update(
            chunk["site"].dropna().unique()
        )

        # Collect vehicle classes
        all_vehicle_classes.update(
            chunk["vehicle_class"].dropna().unique()
        )

        # Collect headings
        all_headings.update(
            chunk["heading"].dropna().unique()
        )

        # Collect speed bins
        all_speed_bins.update(
            chunk["speed_bin"].dropna().unique()
        )

        # Add traffic volume
        total_volume += chunk["volume"].sum()

    file_information.append({
        "File": file.name,
        "Rows": file_rows,
        "Dates_In_File": len(file_dates)
    })


# Convert file information to a table
file_information_df = pd.DataFrame(
    file_information
)


print("\n" + "=" * 70)
print("TIRTL DATA COVERAGE")
print("=" * 70)

print("\nFILES AND STRUCTURE")

print("CSV files checked:", len(tirtl_files))
print("Different column structures:", len(different_structures))
print("Total rows:", f"{total_rows:,}")


print("\nDATE COVERAGE")

print("Earliest date:", earliest_date)
print("Latest date:", latest_date)
print("Unique dates represented:", len(date_records))


print("\nTRAFFIC MONITORING")

print("Unique sites:", len(all_sites))
print(
    "Site IDs:",
    sorted(all_sites)
)

print(
    "Headings:",
    sorted(all_headings)
)

print(
    "Vehicle class codes:",
    sorted(all_vehicle_classes)
)

print(
    "Number of speed bins:",
    len(all_speed_bins)
)

print(
    "Total recorded traffic volume:",
    f"{total_volume:,}"
)


print("\nFILE SIZE SUMMARY")

print(
    "Smallest file:",
    f"{file_information_df['Rows'].min():,}",
    "rows"
)

print(
    "Largest file:",
    f"{file_information_df['Rows'].max():,}",
    "rows"
)

print(
    "Average file size:",
    f"{file_information_df['Rows'].mean():,.0f}",
    "rows"
)


print("\nFIRST 10 FILES")

display(
    file_information_df.head(10)
)

Processing file 1/215: TIRTLDATA_20260401.csv
Processing file 2/215: TIRTLDATA_20260402.csv
Processing file 3/215: TIRTLDATA_20260403.csv
Processing file 4/215: TIRTLDATA_20260404.csv
Processing file 5/215: TIRTLDATA_20260405.csv
Processing file 6/215: TIRTLDATA_20260406.csv
Processing file 7/215: TIRTLDATA_20260407.csv
Processing file 8/215: TIRTLDATA_20260408.csv
Processing file 9/215: TIRTLDATA_20260409.csv
Processing file 10/215: TIRTLDATA_20260410.csv
Processing file 11/215: TIRTLDATA_20260411.csv
Processing file 12/215: TIRTLDATA_20260412.csv
Processing file 13/215: TIRTLDATA_20260413.csv
Processing file 14/215: TIRTLDATA_20260414.csv
Processing file 15/215: TIRTLDATA_20260415.csv
Processing file 16/215: TIRTLDATA_20260416.csv
Processing file 17/215: TIRTLDATA_20260417.csv
Processing file 18/215: TIRTLDATA_20260418.csv
Processing file 19/215: TIRTLDATA_20260419.csv
Processing file 20/215: TIRTLDATA_20260420.csv
Processing file 21/215: TIRTLDATA_20260421.csv
Processing file 22/215: TIRTLDATA_20260422.csv
Processing file 23/215: TIRTLDATA_20260423.csv
Processing file 24/215: TIRTLDATA_20260424.csv
Processing file 25/215: TIRTLDATA_20260425.csv
Processing file 26/215: TIRTLDATA_20260426.csv
Processing file 27/215: TIRTLDATA_20260427.csv
Processing file 28/215: TIRTLDATA_20260428.csv
Processing file 29/215: TIRTLDATA_20260429.csv
Processing file 30/215: TIRTLDATA_20260430.csv
Processing file 31/215: TIRTLDATA_20260801.csv
Processing file 32/215: TIRTLDATA_20260802.csv
Processing file 33/215: TIRTLDATA_20260803.csv
Processing file 34/215: TIRTLDATA_20260804.csv
Processing file 35/215: TIRTLDATA_20260805.csv
Processing file 36/215: TIRTLDATA_20260201.csv
Processing file 37/215: TIRTLDATA_20260202.csv
Processing file 38/215: TIRTLDATA_20260203.csv
Processing file 39/215: TIRTLDATA_20260204.csv
Processing file 40/215: TIRTLDATA_20260205.csv
Processing file 41/215: TIRTLDATA_20260206.csv
Processing file 42/215: TIRTLDATA_20260207.csv
Processing file 43/215: TIRTLDATA_20260208.csv
Processing file 44/215: TIRTLDATA_20260209.csv
Processing file 45/215: TIRTLDATA_20260210.csv
Processing file 46/215: TIRTLDATA_20260211.csv
Processing file 47/215: TIRTLDATA_20260212.csv
Processing file 48/215: TIRTLDATA_20260213.csv
Processing file 49/215: TIRTLDATA_20260214.csv
Processing file 50/215: TIRTLDATA_20260215.csv
Processing file 51/215: TIRTLDATA_20260216.csv
Processing file 52/215: TIRTLDATA_20260217.csv
Processing file 53/215: TIRTLDATA_20260218.csv
Processing file 54/215: TIRTLDATA_20260219.csv
Processing file 55/215: TIRTLDATA_20260220.csv
Processing file 56/215: TIRTLDATA_20260221.csv
Processing file 57/215: TIRTLDATA_20260222.csv
Processing file 58/215: TIRTLDATA_20260223.csv
Processing file 59/215: TIRTLDATA_20260224.csv
Processing file 60/215: TIRTLDATA_20260225.csv
Processing file 61/215: TIRTLDATA_20260226.csv
Processing file 62/215: TIRTLDATA_20260227.csv
Processing file 63/215: TIRTLDATA_20260228.csv
Processing file 64/215: TIRTLDATA_20260101.csv
Processing file 65/215: TIRTLDATA_20260102.csv
Processing file 66/215: TIRTLDATA_20260103.csv
Processing file 67/215: TIRTLDATA_20260104.csv
Processing file 68/215: TIRTLDATA_20260105.csv
Processing file 69/215: TIRTLDATA_20260106.csv
Processing file 70/215: TIRTLDATA_20260107.csv
Processing file 71/215: TIRTLDATA_20260108.csv
Processing file 72/215: TIRTLDATA_20260109.csv
Processing file 73/215: TIRTLDATA_20260110.csv
Processing file 74/215: TIRTLDATA_20260111.csv
Processing file 75/215: TIRTLDATA_20260112.csv
Processing file 76/215: TIRTLDATA_20260113.csv
Processing file 77/215: TIRTLDATA_20260114.csv
Processing file 78/215: TIRTLDATA_20260115.csv
Processing file 79/215: TIRTLDATA_20260116.csv
Processing file 80/215: TIRTLDATA_20260117.csv
Processing file 81/215: TIRTLDATA_20260118.csv
Processing file 82/215: TIRTLDATA_20260119.csv
Processing file 83/215: TIRTLDATA_20260120.csv
Processing file 84/215: TIRTLDATA_20260121.csv
Processing file 85/215: TIRTLDATA_20260122.csv
Processing file 86/215: TIRTLDATA_20260123.csv
Processing file 87/215: TIRTLDATA_20260124.csv
Processing file 88/215: TIRTLDATA_20260125.csv
Processing file 89/215: TIRTLDATA_20260126.csv
Processing file 90/215: TIRTLDATA_20260127.csv
Processing file 91/215: TIRTLDATA_20260128.csv
Processing file 92/215: TIRTLDATA_20260129.csv
Processing file 93/215: TIRTLDATA_20260130.csv
Processing file 94/215: TIRTLDATA_20260131.csv
Processing file 95/215: TIRTLDATA_20260701.csv
Processing file 96/215: TIRTLDATA_20260702.csv
Processing file 97/215: TIRTLDATA_20260703.csv
Processing file 98/215: TIRTLDATA_20260704.csv
Processing file 99/215: TIRTLDATA_20260705.csv
Processing file 100/215: TIRTLDATA_20260706.csv
Processing file 101/215: TIRTLDATA_20260707.csv
Processing file 102/215: TIRTLDATA_20260708.csv
Processing file 103/215: TIRTLDATA_20260709.csv
Processing file 104/215: TIRTLDATA_20260710.csv
Processing file 105/215: TIRTLDATA_20260711.csv
Processing file 106/215: TIRTLDATA_20260712.csv
Processing file 107/215: TIRTLDATA_20260713.csv
Processing file 108/215: TIRTLDATA_20260714.csv
Processing file 109/215: TIRTLDATA_20260715.csv
Processing file 110/215: TIRTLDATA_20260716.csv
Processing file 111/215: TIRTLDATA_20260717.csv
Processing file 112/215: TIRTLDATA_20260718.csv
Processing file 113/215: TIRTLDATA_20260719.csv
Processing file 114/215: TIRTLDATA_20260720.csv
Processing file 115/215: TIRTLDATA_20260721.csv
Processing file 116/215: TIRTLDATA_20260722.csv
Processing file 117/215: TIRTLDATA_20260723.csv
Processing file 118/215: TIRTLDATA_20260724.csv
Processing file 119/215: TIRTLDATA_20260725.csv
Processing file 120/215: TIRTLDATA_20260726.csv
Processing file 121/215: TIRTLDATA_20260727.csv
Processing file 122/215: TIRTLDATA_20260728.csv
Processing file 123/215: TIRTLDATA_20260729.csv
Processing file 124/215: TIRTLDATA_20260601.csv
Processing file 125/215: TIRTLDATA_20260602.csv
Processing file 126/215: TIRTLDATA_20260603.csv
Processing file 127/215: TIRTLDATA_20260604.csv
Processing file 128/215: TIRTLDATA_20260605.csv
Processing file 129/215: TIRTLDATA_20260606.csv
Processing file 130/215: TIRTLDATA_20260607.csv
Processing file 131/215: TIRTLDATA_20260608.csv
Processing file 132/215: TIRTLDATA_20260609.csv
Processing file 133/215: TIRTLDATA_20260610.csv
Processing file 134/215: TIRTLDATA_20260611.csv
Processing file 135/215: TIRTLDATA_20260612.csv
Processing file 136/215: TIRTLDATA_20260613.csv
Processing file 137/215: TIRTLDATA_20260614.csv
Processing file 138/215: TIRTLDATA_20260615.csv
Processing file 139/215: TIRTLDATA_20260616.csv
Processing file 140/215: TIRTLDATA_20260617.csv
Processing file 141/215: TIRTLDATA_20260618.csv
Processing file 142/215: TIRTLDATA_20260619.csv
Processing file 143/215: TIRTLDATA_20260620.csv
Processing file 144/215: TIRTLDATA_20260621.csv
Processing file 145/215: TIRTLDATA_20260622.csv
Processing file 146/215: TIRTLDATA_20260623.csv
Processing file 147/215: TIRTLDATA_20260624.csv
Processing file 148/215: TIRTLDATA_20260625.csv
Processing file 149/215: TIRTLDATA_20260626.csv
Processing file 150/215: TIRTLDATA_20260627.csv
Processing file 151/215: TIRTLDATA_20260628.csv
Processing file 152/215: TIRTLDATA_20260629.csv
Processing file 153/215: TIRTLDATA_20260630.csv
Processing file 154/215: TIRTLDATA_20260301.csv
Processing file 155/215: TIRTLDATA_20260302.csv
Processing file 156/215: TIRTLDATA_20260303.csv
Processing file 157/215: TIRTLDATA_20260304.csv
Processing file 158/215: TIRTLDATA_20260305.csv
Processing file 159/215: TIRTLDATA_20260306.csv
Processing file 160/215: TIRTLDATA_20260307.csv
Processing file 161/215: TIRTLDATA_20260308.csv
Processing file 162/215: TIRTLDATA_20260309.csv
Processing file 163/215: TIRTLDATA_20260310.csv
Processing file 164/215: TIRTLDATA_20260311.csv
Processing file 165/215: TIRTLDATA_20260312.csv
Processing file 166/215: TIRTLDATA_20260313.csv
Processing file 167/215: TIRTLDATA_20260314.csv
Processing file 168/215: TIRTLDATA_20260315.csv
Processing file 169/215: TIRTLDATA_20260316.csv
Processing file 170/215: TIRTLDATA_20260317.csv
Processing file 171/215: TIRTLDATA_20260318.csv
Processing file 172/215: TIRTLDATA_20260319.csv
Processing file 173/215: TIRTLDATA_20260320.csv
Processing file 174/215: TIRTLDATA_20260321.csv
Processing file 175/215: TIRTLDATA_20260322.csv
Processing file 176/215: TIRTLDATA_20260323.csv
Processing file 177/215: TIRTLDATA_20260324.csv
Processing file 178/215: TIRTLDATA_20260325.csv
Processing file 179/215: TIRTLDATA_20260326.csv
Processing file 180/215: TIRTLDATA_20260327.csv
Processing file 181/215: TIRTLDATA_20260328.csv
Processing file 182/215: TIRTLDATA_20260329.csv
Processing file 183/215: TIRTLDATA_20260330.csv
Processing file 184/215: TIRTLDATA_20260331.csv
Processing file 185/215: TIRTLDATA_20260501.csv
Processing file 186/215: TIRTLDATA_20260502.csv
Processing file 187/215: TIRTLDATA_20260503.csv
Processing file 188/215: TIRTLDATA_20260504.csv
Processing file 189/215: TIRTLDATA_20260505.csv
Processing file 190/215: TIRTLDATA_20260506.csv
Processing file 191/215: TIRTLDATA_20260507.csv
Processing file 192/215: TIRTLDATA_20260508.csv
Processing file 193/215: TIRTLDATA_20260509.csv
Processing file 194/215: TIRTLDATA_20260510.csv
Processing file 195/215: TIRTLDATA_20260511.csv
Processing file 196/215: TIRTLDATA_20260512.csv
Processing file 197/215: TIRTLDATA_20260513.csv
Processing file 198/215: TIRTLDATA_20260514.csv
Processing file 199/215: TIRTLDATA_20260515.csv
Processing file 200/215: TIRTLDATA_20260516.csv
Processing file 201/215: TIRTLDATA_20260517.csv
Processing file 202/215: TIRTLDATA_20260518.csv
Processing file 203/215: TIRTLDATA_20260519.csv
Processing file 204/215: TIRTLDATA_20260520.csv
Processing file 205/215: TIRTLDATA_20260521.csv
Processing file 206/215: TIRTLDATA_20260522.csv
Processing file 207/215: TIRTLDATA_20260523.csv
Processing file 208/215: TIRTLDATA_20260524.csv
Processing file 209/215: TIRTLDATA_20260525.csv
Processing file 210/215: TIRTLDATA_20260526.csv
Processing file 211/215: TIRTLDATA_20260527.csv
Processing file 212/215: TIRTLDATA_20260528.csv
Processing file 213/215: TIRTLDATA_20260529.csv
Processing file 214/215: TIRTLDATA_20260530.csv
Processing file 215/215: TIRTLDATA_20260531.csv

======================================================================
TIRTL DATA COVERAGE
======================================================================

FILES AND STRUCTURE
CSV files checked: 215
Different column structures: 1
Total rows: 211,284,853

DATE COVERAGE
Earliest date: 2026-01-01 00:00:00
Latest date: 2026-08-05 00:00:00
Unique dates represented: 215

TRAFFIC MONITORING
Unique sites: 303
Site IDs: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 82, 83, 84, 85, 86, 87, 89, 90, 91, 92, 93, 94, 96, 98, 99, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 151, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 213, 214, 215, 216, 217, 219, 220, 221, 222, 223, 225, 226, 227, 228, 229, 230, 231, 233, 234, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 273, 276, 279, 280, 281, 282, 283, 287, 288, 289, 292, 293, 306, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 504, 505, 530, 531, 555, 556, 562, 563, 564, 565, 566, 567, 568, 569, 570, 580, 581]
Headings: ['E', 'N', 'S', 'W']
Vehicle class codes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Number of speed bins: 31
Total recorded traffic volume: 3,611,072,689

FILE SIZE SUMMARY
Smallest file: 623,460 rows
Largest file: 1,190,270 rows
Average file size: 982,720 rows

FIRST 10 FILES

                     File     Rows  Dates_In_File
0  TIRTLDATA_20260401.csv  1160005              1
1  TIRTLDATA_20260402.csv  1184145              1
2  TIRTLDATA_20260403.csv   685037              1
3  TIRTLDATA_20260404.csv   679487              1
4  TIRTLDATA_20260405.csv   623460              1
5  TIRTLDATA_20260406.csv   728207              1
6  TIRTLDATA_20260407.csv  1034582              1
7  TIRTLDATA_20260408.csv  1030425              1
8  TIRTLDATA_20260409.csv  1068753              1
9  TIRTLDATA_20260410.csv  1057132              1

In [27]:
# CELL 4: Check data quality across the TIRTL Traffic Count files

from collections import Counter

# Counters for missing values
missing_values = Counter()

# Other quality checks
negative_volume = 0
zero_volume = 0
invalid_dates = 0
invalid_times = 0
unexpected_headings = 0

# Track possible duplicate rows
duplicate_rows = 0

# Track sites available on each date
sites_per_date = {}

# Track total volume by month
monthly_volume = Counter()

# Track total volume by heading
heading_volume = Counter()

# Track total volume by vehicle class
vehicle_class_volume = Counter()

rows_checked = 0

expected_headings = {"N", "S", "E", "W"}


for number, file in enumerate(tirtl_files, start=1):

    print(
        f"Checking file {number}/{len(tirtl_files)}:",
        file.name
    )

    for chunk in pd.read_csv(
        file,
        chunksize=200_000,
        low_memory=False
    ):

        rows_checked += len(chunk)

        # ---------------------------------------------------------
        # Missing values
        # ---------------------------------------------------------

        chunk_missing = chunk.isna().sum()

        for column, value in chunk_missing.items():
            missing_values[column] += int(value)


        # ---------------------------------------------------------
        # Volume checks
        # ---------------------------------------------------------

        numeric_volume = pd.to_numeric(
            chunk["volume"],
            errors="coerce"
        )

        negative_volume += int(
            (numeric_volume < 0).sum()
        )

        zero_volume += int(
            (numeric_volume == 0).sum()
        )


        # ---------------------------------------------------------
        # Date checks
        # ---------------------------------------------------------

        parsed_dates = pd.to_datetime(
            chunk["date"],
            errors="coerce"
        )

        invalid_dates += int(
            parsed_dates.isna().sum()
        )


        # ---------------------------------------------------------
        # Time-bin checks
        # ---------------------------------------------------------

        parsed_times = pd.to_datetime(
            chunk["time_bin"],
            format="%H:%M",
            errors="coerce"
        )

        invalid_times += int(
            parsed_times.isna().sum()
        )


        # ---------------------------------------------------------
        # Heading checks
        # ---------------------------------------------------------

        headings = set(
            chunk["heading"]
            .dropna()
            .astype(str)
            .unique()
        )

        invalid_heading_values = (
            headings - expected_headings
        )

        if invalid_heading_values:

            unexpected_headings += int(
                chunk["heading"]
                .astype(str)
                .isin(invalid_heading_values)
                .sum()
            )


        # ---------------------------------------------------------
        # Duplicate check within each chunk
        # ---------------------------------------------------------

        duplicate_rows += int(
            chunk.duplicated().sum()
        )


        # ---------------------------------------------------------
        # Sites available per date
        # ---------------------------------------------------------

        valid_date_rows = chunk.loc[
            parsed_dates.notna()
        ].copy()

        valid_date_rows["_parsed_date"] = (
            parsed_dates[
                parsed_dates.notna()
            ].dt.date.values
        )

        for date_value, group in valid_date_rows.groupby(
            "_parsed_date"
        ):

            if date_value not in sites_per_date:
                sites_per_date[date_value] = set()

            sites_per_date[date_value].update(
                group["site"]
                .dropna()
                .unique()
            )


        # ---------------------------------------------------------
        # Monthly traffic volume
        # ---------------------------------------------------------

        valid_month_mask = (
            parsed_dates.notna() &
            numeric_volume.notna()
        )

        months = parsed_dates[
            valid_month_mask
        ].dt.to_period("M").astype(str)

        month_values = (
            pd.DataFrame({
                "month": months.values,
                "volume": numeric_volume[
                    valid_month_mask
                ].values
            })
            .groupby("month")["volume"]
            .sum()
        )

        for month, value in month_values.items():
            monthly_volume[month] += int(value)


        # ---------------------------------------------------------
        # Traffic volume by heading
        # ---------------------------------------------------------

        heading_summary = (
            chunk.assign(
                _volume=numeric_volume
            )
            .groupby("heading")["_volume"]
            .sum()
        )

        for heading, value in heading_summary.items():

            if pd.notna(value):
                heading_volume[heading] += int(value)


        # ---------------------------------------------------------
        # Traffic volume by vehicle class
        # ---------------------------------------------------------

        class_summary = (
            chunk.assign(
                _volume=numeric_volume
            )
            .groupby("vehicle_class")["_volume"]
            .sum()
        )

        for vehicle_class, value in class_summary.items():

            if pd.notna(value):
                vehicle_class_volume[
                    vehicle_class
                ] += int(value)


# -------------------------------------------------------------
# Create missing-value summary
# -------------------------------------------------------------

missing_summary_tirtl = pd.DataFrame({
    "Column": expected_columns,
    "Missing_Values": [
        missing_values[column]
        for column in expected_columns
    ]
})

missing_summary_tirtl[
    "Missing_Percentage"
] = (
    missing_summary_tirtl[
        "Missing_Values"
    ] / rows_checked * 100
).round(4)


# -------------------------------------------------------------
# Site coverage table
# -------------------------------------------------------------

site_coverage_tirtl = pd.DataFrame([
    {
        "Date": date_value,
        "Unique_Sites": len(site_set)
    }
    for date_value, site_set
    in sorted(sites_per_date.items())
])


# -------------------------------------------------------------
# Monthly volume table
# -------------------------------------------------------------

monthly_volume_tirtl = pd.DataFrame(
    sorted(monthly_volume.items()),
    columns=[
        "Month",
        "Total_Volume"
    ]
)


# -------------------------------------------------------------
# Vehicle class table
# -------------------------------------------------------------

vehicle_class_tirtl = pd.DataFrame(
    sorted(vehicle_class_volume.items()),
    columns=[
        "Vehicle_Class",
        "Total_Volume"
    ]
)

vehicle_class_tirtl = (
    vehicle_class_tirtl
    .sort_values(
        "Total_Volume",
        ascending=False
    )
    .reset_index(drop=True)
)


# -------------------------------------------------------------
# Display results
# -------------------------------------------------------------

print("\n" + "=" * 70)
print("TIRTL DATA QUALITY")
print("=" * 70)

print("\nTotal rows checked:", f"{rows_checked:,}")


print("\nMISSING VALUES")

display(missing_summary_tirtl)


print("\nVOLUME CHECK")

print(
    "Negative volume values:",
    f"{negative_volume:,}"
)

print(
    "Zero volume values:",
    f"{zero_volume:,}"
)


print("\nDATE AND TIME CHECK")

print(
    "Invalid dates:",
    f"{invalid_dates:,}"
)

print(
    "Invalid time bins:",
    f"{invalid_times:,}"
)


print("\nHEADING CHECK")

print(
    "Rows with unexpected headings:",
    f"{unexpected_headings:,}"
)


print("\nDUPLICATE CHECK")

print(
    "Potential duplicate rows found within chunks:",
    f"{duplicate_rows:,}"
)


print("\nSITE COVERAGE")

print(
    "Minimum sites recorded on a day:",
    site_coverage_tirtl[
        "Unique_Sites"
    ].min()
)

print(
    "Maximum sites recorded on a day:",
    site_coverage_tirtl[
        "Unique_Sites"
    ].max()
)

print(
    "Average sites recorded per day:",
    round(
        site_coverage_tirtl[
            "Unique_Sites"
        ].mean(),
        2
    )
)


print("\nMONTHLY RECORDED TRAFFIC VOLUME")

display(monthly_volume_tirtl)


print("\nTRAFFIC VOLUME BY HEADING")

for heading, value in sorted(
    heading_volume.items()
):
    print(
        f"{heading}: {value:,}"
    )


print("\nTRAFFIC VOLUME BY VEHICLE CLASS CODE")

display(vehicle_class_tirtl)

Checking file 1/215: TIRTLDATA_20260401.csv
Checking file 2/215: TIRTLDATA_20260402.csv
Checking file 3/215: TIRTLDATA_20260403.csv
Checking file 4/215: TIRTLDATA_20260404.csv
Checking file 5/215: TIRTLDATA_20260405.csv
Checking file 6/215: TIRTLDATA_20260406.csv
Checking file 7/215: TIRTLDATA_20260407.csv
Checking file 8/215: TIRTLDATA_20260408.csv
Checking file 9/215: TIRTLDATA_20260409.csv
Checking file 10/215: TIRTLDATA_20260410.csv
Checking file 11/215: TIRTLDATA_20260411.csv
Checking file 12/215: TIRTLDATA_20260412.csv
Checking file 13/215: TIRTLDATA_20260413.csv
Checking file 14/215: TIRTLDATA_20260414.csv
Checking file 15/215: TIRTLDATA_20260415.csv
Checking file 16/215: TIRTLDATA_20260416.csv
Checking file 17/215: TIRTLDATA_20260417.csv
Checking file 18/215: TIRTLDATA_20260418.csv
Checking file 19/215: TIRTLDATA_20260419.csv
Checking file 20/215: TIRTLDATA_20260420.csv
Checking file 21/215: TIRTLDATA_20260421.csv
Checking file 22/215: TIRTLDATA_20260422.csv
Checking file 23/215: TIRTLDATA_20260423.csv
Checking file 24/215: TIRTLDATA_20260424.csv
Checking file 25/215: TIRTLDATA_20260425.csv
Checking file 26/215: TIRTLDATA_20260426.csv
Checking file 27/215: TIRTLDATA_20260427.csv
Checking file 28/215: TIRTLDATA_20260428.csv
Checking file 29/215: TIRTLDATA_20260429.csv
Checking file 30/215: TIRTLDATA_20260430.csv
Checking file 31/215: TIRTLDATA_20260801.csv
Checking file 32/215: TIRTLDATA_20260802.csv
Checking file 33/215: TIRTLDATA_20260803.csv
Checking file 34/215: TIRTLDATA_20260804.csv
Checking file 35/215: TIRTLDATA_20260805.csv
Checking file 36/215: TIRTLDATA_20260201.csv
Checking file 37/215: TIRTLDATA_20260202.csv
Checking file 38/215: TIRTLDATA_20260203.csv
Checking file 39/215: TIRTLDATA_20260204.csv
Checking file 40/215: TIRTLDATA_20260205.csv
Checking file 41/215: TIRTLDATA_20260206.csv
Checking file 42/215: TIRTLDATA_20260207.csv
Checking file 43/215: TIRTLDATA_20260208.csv
Checking file 44/215: TIRTLDATA_20260209.csv
Checking file 45/215: TIRTLDATA_20260210.csv
Checking file 46/215: TIRTLDATA_20260211.csv
Checking file 47/215: TIRTLDATA_20260212.csv
Checking file 48/215: TIRTLDATA_20260213.csv
Checking file 49/215: TIRTLDATA_20260214.csv
Checking file 50/215: TIRTLDATA_20260215.csv
Checking file 51/215: TIRTLDATA_20260216.csv
Checking file 52/215: TIRTLDATA_20260217.csv
Checking file 53/215: TIRTLDATA_20260218.csv
Checking file 54/215: TIRTLDATA_20260219.csv
Checking file 55/215: TIRTLDATA_20260220.csv
Checking file 56/215: TIRTLDATA_20260221.csv
Checking file 57/215: TIRTLDATA_20260222.csv
Checking file 58/215: TIRTLDATA_20260223.csv
Checking file 59/215: TIRTLDATA_20260224.csv
Checking file 60/215: TIRTLDATA_20260225.csv
Checking file 61/215: TIRTLDATA_20260226.csv
Checking file 62/215: TIRTLDATA_20260227.csv
Checking file 63/215: TIRTLDATA_20260228.csv
Checking file 64/215: TIRTLDATA_20260101.csv
Checking file 65/215: TIRTLDATA_20260102.csv
Checking file 66/215: TIRTLDATA_20260103.csv
Checking file 67/215: TIRTLDATA_20260104.csv
Checking file 68/215: TIRTLDATA_20260105.csv
Checking file 69/215: TIRTLDATA_20260106.csv
Checking file 70/215: TIRTLDATA_20260107.csv
Checking file 71/215: TIRTLDATA_20260108.csv
Checking file 72/215: TIRTLDATA_20260109.csv
Checking file 73/215: TIRTLDATA_20260110.csv
Checking file 74/215: TIRTLDATA_20260111.csv
Checking file 75/215: TIRTLDATA_20260112.csv
Checking file 76/215: TIRTLDATA_20260113.csv
Checking file 77/215: TIRTLDATA_20260114.csv
Checking file 78/215: TIRTLDATA_20260115.csv
Checking file 79/215: TIRTLDATA_20260116.csv
Checking file 80/215: TIRTLDATA_20260117.csv
Checking file 81/215: TIRTLDATA_20260118.csv
Checking file 82/215: TIRTLDATA_20260119.csv
Checking file 83/215: TIRTLDATA_20260120.csv
Checking file 84/215: TIRTLDATA_20260121.csv
Checking file 85/215: TIRTLDATA_20260122.csv
Checking file 86/215: TIRTLDATA_20260123.csv
Checking file 87/215: TIRTLDATA_20260124.csv
Checking file 88/215: TIRTLDATA_20260125.csv
Checking file 89/215: TIRTLDATA_20260126.csv
Checking file 90/215: TIRTLDATA_20260127.csv
Checking file 91/215: TIRTLDATA_20260128.csv
Checking file 92/215: TIRTLDATA_20260129.csv
Checking file 93/215: TIRTLDATA_20260130.csv
Checking file 94/215: TIRTLDATA_20260131.csv
Checking file 95/215: TIRTLDATA_20260701.csv
Checking file 96/215: TIRTLDATA_20260702.csv
Checking file 97/215: TIRTLDATA_20260703.csv
Checking file 98/215: TIRTLDATA_20260704.csv
Checking file 99/215: TIRTLDATA_20260705.csv
Checking file 100/215: TIRTLDATA_20260706.csv
Checking file 101/215: TIRTLDATA_20260707.csv
Checking file 102/215: TIRTLDATA_20260708.csv
Checking file 103/215: TIRTLDATA_20260709.csv
Checking file 104/215: TIRTLDATA_20260710.csv
Checking file 105/215: TIRTLDATA_20260711.csv
Checking file 106/215: TIRTLDATA_20260712.csv
Checking file 107/215: TIRTLDATA_20260713.csv
Checking file 108/215: TIRTLDATA_20260714.csv
Checking file 109/215: TIRTLDATA_20260715.csv
Checking file 110/215: TIRTLDATA_20260716.csv
Checking file 111/215: TIRTLDATA_20260717.csv
Checking file 112/215: TIRTLDATA_20260718.csv
Checking file 113/215: TIRTLDATA_20260719.csv
Checking file 114/215: TIRTLDATA_20260720.csv
Checking file 115/215: TIRTLDATA_20260721.csv
Checking file 116/215: TIRTLDATA_20260722.csv
Checking file 117/215: TIRTLDATA_20260723.csv
Checking file 118/215: TIRTLDATA_20260724.csv
Checking file 119/215: TIRTLDATA_20260725.csv
Checking file 120/215: TIRTLDATA_20260726.csv
Checking file 121/215: TIRTLDATA_20260727.csv
Checking file 122/215: TIRTLDATA_20260728.csv
Checking file 123/215: TIRTLDATA_20260729.csv
Checking file 124/215: TIRTLDATA_20260601.csv
Checking file 125/215: TIRTLDATA_20260602.csv
Checking file 126/215: TIRTLDATA_20260603.csv
Checking file 127/215: TIRTLDATA_20260604.csv
Checking file 128/215: TIRTLDATA_20260605.csv
Checking file 129/215: TIRTLDATA_20260606.csv
Checking file 130/215: TIRTLDATA_20260607.csv
Checking file 131/215: TIRTLDATA_20260608.csv
Checking file 132/215: TIRTLDATA_20260609.csv
Checking file 133/215: TIRTLDATA_20260610.csv
Checking file 134/215: TIRTLDATA_20260611.csv
Checking file 135/215: TIRTLDATA_20260612.csv
Checking file 136/215: TIRTLDATA_20260613.csv
Checking file 137/215: TIRTLDATA_20260614.csv
Checking file 138/215: TIRTLDATA_20260615.csv
Checking file 139/215: TIRTLDATA_20260616.csv
Checking file 140/215: TIRTLDATA_20260617.csv
Checking file 141/215: TIRTLDATA_20260618.csv
Checking file 142/215: TIRTLDATA_20260619.csv
Checking file 143/215: TIRTLDATA_20260620.csv
Checking file 144/215: TIRTLDATA_20260621.csv
Checking file 145/215: TIRTLDATA_20260622.csv
Checking file 146/215: TIRTLDATA_20260623.csv
Checking file 147/215: TIRTLDATA_20260624.csv
Checking file 148/215: TIRTLDATA_20260625.csv
Checking file 149/215: TIRTLDATA_20260626.csv
Checking file 150/215: TIRTLDATA_20260627.csv
Checking file 151/215: TIRTLDATA_20260628.csv
Checking file 152/215: TIRTLDATA_20260629.csv
Checking file 153/215: TIRTLDATA_20260630.csv
Checking file 154/215: TIRTLDATA_20260301.csv
Checking file 155/215: TIRTLDATA_20260302.csv
Checking file 156/215: TIRTLDATA_20260303.csv
Checking file 157/215: TIRTLDATA_20260304.csv
Checking file 158/215: TIRTLDATA_20260305.csv
Checking file 159/215: TIRTLDATA_20260306.csv
Checking file 160/215: TIRTLDATA_20260307.csv
Checking file 161/215: TIRTLDATA_20260308.csv
Checking file 162/215: TIRTLDATA_20260309.csv
Checking file 163/215: TIRTLDATA_20260310.csv
Checking file 164/215: TIRTLDATA_20260311.csv
Checking file 165/215: TIRTLDATA_20260312.csv
Checking file 166/215: TIRTLDATA_20260313.csv
Checking file 167/215: TIRTLDATA_20260314.csv
Checking file 168/215: TIRTLDATA_20260315.csv
Checking file 169/215: TIRTLDATA_20260316.csv
Checking file 170/215: TIRTLDATA_20260317.csv
Checking file 171/215: TIRTLDATA_20260318.csv
Checking file 172/215: TIRTLDATA_20260319.csv
Checking file 173/215: TIRTLDATA_20260320.csv
Checking file 174/215: TIRTLDATA_20260321.csv
Checking file 175/215: TIRTLDATA_20260322.csv
Checking file 176/215: TIRTLDATA_20260323.csv
Checking file 177/215: TIRTLDATA_20260324.csv
Checking file 178/215: TIRTLDATA_20260325.csv
Checking file 179/215: TIRTLDATA_20260326.csv
Checking file 180/215: TIRTLDATA_20260327.csv
Checking file 181/215: TIRTLDATA_20260328.csv
Checking file 182/215: TIRTLDATA_20260329.csv
Checking file 183/215: TIRTLDATA_20260330.csv
Checking file 184/215: TIRTLDATA_20260331.csv
Checking file 185/215: TIRTLDATA_20260501.csv
Checking file 186/215: TIRTLDATA_20260502.csv
Checking file 187/215: TIRTLDATA_20260503.csv
Checking file 188/215: TIRTLDATA_20260504.csv
Checking file 189/215: TIRTLDATA_20260505.csv
Checking file 190/215: TIRTLDATA_20260506.csv
Checking file 191/215: TIRTLDATA_20260507.csv
Checking file 192/215: TIRTLDATA_20260508.csv
Checking file 193/215: TIRTLDATA_20260509.csv
Checking file 194/215: TIRTLDATA_20260510.csv
Checking file 195/215: TIRTLDATA_20260511.csv
Checking file 196/215: TIRTLDATA_20260512.csv
Checking file 197/215: TIRTLDATA_20260513.csv
Checking file 198/215: TIRTLDATA_20260514.csv
Checking file 199/215: TIRTLDATA_20260515.csv
Checking file 200/215: TIRTLDATA_20260516.csv
Checking file 201/215: TIRTLDATA_20260517.csv
Checking file 202/215: TIRTLDATA_20260518.csv
Checking file 203/215: TIRTLDATA_20260519.csv
Checking file 204/215: TIRTLDATA_20260520.csv
Checking file 205/215: TIRTLDATA_20260521.csv
Checking file 206/215: TIRTLDATA_20260522.csv
Checking file 207/215: TIRTLDATA_20260523.csv
Checking file 208/215: TIRTLDATA_20260524.csv
Checking file 209/215: TIRTLDATA_20260525.csv
Checking file 210/215: TIRTLDATA_20260526.csv
Checking file 211/215: TIRTLDATA_20260527.csv
Checking file 212/215: TIRTLDATA_20260528.csv
Checking file 213/215: TIRTLDATA_20260529.csv
Checking file 214/215: TIRTLDATA_20260530.csv
Checking file 215/215: TIRTLDATA_20260531.csv

======================================================================
TIRTL DATA QUALITY
======================================================================

Total rows checked: 211,284,853

MISSING VALUES

          Column  Missing_Values  Missing_Percentage
0           date               0                 0.0
1       time_bin               0                 0.0
2           site               0                 0.0
3        heading               0                 0.0
4  vehicle_class               0                 0.0
5      speed_bin               0                 0.0
6         volume               0                 0.0

VOLUME CHECK
Negative volume values: 0
Zero volume values: 0

DATE AND TIME CHECK
Invalid dates: 0
Invalid time bins: 0

HEADING CHECK
Rows with unexpected headings: 0

DUPLICATE CHECK
Potential duplicate rows found within chunks: 0

SITE COVERAGE
Minimum sites recorded on a day: 275
Maximum sites recorded on a day: 292
Average sites recorded per day: 286.28

MONTHLY RECORDED TRAFFIC VOLUME

     Month  Total_Volume
0  2026-01     514997294
1  2026-02     496601945
2  2026-03     527082717
3  2026-04     480822073
4  2026-05     512161106
5  2026-06     500705916
6  2026-07     496488261
7  2026-08      82213377

TRAFFIC VOLUME BY HEADING
E: 1,631,313,339
N: 192,587,961
S: 185,486,942
W: 1,601,684,447

TRAFFIC VOLUME BY VEHICLE CLASS CODE

    Vehicle_Class  Total_Volume
0               1    3019852979
1               3     355039100
2               9      61301304
3               4      38588541
4              10      38210124
5               2      34354259
6               0      14357498
7               7      12699106
8               5      12188849
9               8       9502705
10              6       8976229
11             11       5841327
12             13        141648
13             14         17756
14             12          1264

In [29]:
# CELL 5: Create hourly traffic summaries and save current analysis outputs

from pathlib import Path
from collections import Counter

# -------------------------------------------------------------
# Containers for aggregated results
# -------------------------------------------------------------

hourly_volume = Counter()
daily_volume = Counter()
hour_of_day_volume = Counter()
hour_of_day_intervals = Counter()

site_volume = Counter()

rows_processed = 0


# -------------------------------------------------------------
# Process each file in manageable chunks
# -------------------------------------------------------------

for number, file in enumerate(tirtl_files, start=1):

    print(
        f"Aggregating file {number}/{len(tirtl_files)}:",
        file.name
    )

    for chunk in pd.read_csv(
        file,
        chunksize=200_000,
        low_memory=False
    ):

        rows_processed += len(chunk)

        # Convert date and time into one timestamp
        timestamp = pd.to_datetime(
            chunk["date"].astype(str)
            + " "
            + chunk["time_bin"].astype(str),
            errors="coerce"
        )

        volume = pd.to_numeric(
            chunk["volume"],
            errors="coerce"
        )

        valid = (
            timestamp.notna()
            & volume.notna()
        )

        temp = pd.DataFrame({
            "timestamp": timestamp[valid],
            "site": chunk.loc[valid, "site"].values,
            "volume": volume[valid].values
        })

        # ---------------------------------------------------------
        # Convert 15-minute observations to hourly periods
        # ---------------------------------------------------------

        temp["hour"] = (
            temp["timestamp"].dt.floor("h")
        )

        temp["date"] = (
            temp["timestamp"].dt.date
        )

        temp["hour_of_day"] = (
            temp["timestamp"].dt.hour
        )


        # ---------------------------------------------------------
        # Total volume for each hour
        # ---------------------------------------------------------

        hourly_chunk = (
            temp.groupby("hour")["volume"]
            .sum()
        )

        for hour, value in hourly_chunk.items():
            hourly_volume[hour] += int(value)


        # ---------------------------------------------------------
        # Daily traffic volume
        # ---------------------------------------------------------

        daily_chunk = (
            temp.groupby("date")["volume"]
            .sum()
        )

        for date_value, value in daily_chunk.items():
            daily_volume[date_value] += int(value)


        # ---------------------------------------------------------
        # Site traffic volume
        # ---------------------------------------------------------

        site_chunk = (
            temp.groupby("site")["volume"]
            .sum()
        )

        for site, value in site_chunk.items():
            site_volume[site] += int(value)


# -------------------------------------------------------------
# Create hourly dataframe
# -------------------------------------------------------------

hourly_tirtl = pd.DataFrame(
    sorted(hourly_volume.items()),
    columns=[
        "Hour",
        "Traffic_Volume"
    ]
)

hourly_tirtl["Hour_of_Day"] = (
    pd.to_datetime(
        hourly_tirtl["Hour"]
    ).dt.hour
)


# -------------------------------------------------------------
# Calculate average traffic by hour of day
# -------------------------------------------------------------

hourly_pattern_tirtl = (
    hourly_tirtl
    .groupby("Hour_of_Day")
    ["Traffic_Volume"]
    .agg(
        Total_Volume="sum",
        Number_of_Hours="count",
        Average_Hourly_Volume="mean"
    )
    .reset_index()
)

hourly_pattern_tirtl[
    "Average_Hourly_Volume"
] = (
    hourly_pattern_tirtl[
        "Average_Hourly_Volume"
    ].round(2)
)


# -------------------------------------------------------------
# Daily dataframe
# -------------------------------------------------------------

daily_tirtl = pd.DataFrame(
    sorted(daily_volume.items()),
    columns=[
        "Date",
        "Traffic_Volume"
    ]
)

daily_tirtl["Date"] = pd.to_datetime(
    daily_tirtl["Date"]
)

daily_tirtl["Day"] = (
    daily_tirtl["Date"]
    .dt.day_name()
)


# -------------------------------------------------------------
# Average daily volume by day of week
# -------------------------------------------------------------

day_pattern_tirtl = (
    daily_tirtl
    .groupby("Day")["Traffic_Volume"]
    .agg(
        Total_Volume="sum",
        Number_of_Days="count",
        Average_Daily_Volume="mean"
    )
    .reset_index()
)

day_order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

day_pattern_tirtl["Day"] = pd.Categorical(
    day_pattern_tirtl["Day"],
    categories=day_order,
    ordered=True
)

day_pattern_tirtl = (
    day_pattern_tirtl
    .sort_values("Day")
    .reset_index(drop=True)
)

day_pattern_tirtl[
    "Average_Daily_Volume"
] = (
    day_pattern_tirtl[
        "Average_Daily_Volume"
    ].round(2)
)


# -------------------------------------------------------------
# Site summary
# -------------------------------------------------------------

site_summary_tirtl = pd.DataFrame(
    sorted(site_volume.items()),
    columns=[
        "Site",
        "Total_Volume"
    ]
)

site_summary_tirtl = (
    site_summary_tirtl
    .sort_values(
        "Total_Volume",
        ascending=False
    )
    .reset_index(drop=True)
)


# -------------------------------------------------------------
# Display useful results
# -------------------------------------------------------------

print("\n" + "=" * 70)
print("CURRENT TIRTL TRAFFIC ANALYSIS")
print("=" * 70)

print(
    "\nRows processed:",
    f"{rows_processed:,}"
)

print(
    "Hourly periods created:",
    f"{len(hourly_tirtl):,}"
)

print(
    "Days represented:",
    f"{len(daily_tirtl):,}"
)


print("\nHOURLY TRAFFIC PATTERN")

display(hourly_pattern_tirtl)


print("\nDAY-OF-WEEK TRAFFIC PATTERN")

display(day_pattern_tirtl)


print("\nTOP 10 SITES BY RECORDED TRAFFIC VOLUME")

display(
    site_summary_tirtl.head(10)
)


# -------------------------------------------------------------
# Identify current peak periods
# -------------------------------------------------------------

peak_hour = hourly_pattern_tirtl.loc[
    hourly_pattern_tirtl[
        "Average_Hourly_Volume"
    ].idxmax()
]

peak_day = day_pattern_tirtl.loc[
    day_pattern_tirtl[
        "Average_Daily_Volume"
    ].idxmax()
]


print("\nCURRENT TRAFFIC PATTERNS")

print(
    "Highest average traffic hour:",
    f"{int(peak_hour['Hour_of_Day']):02d}:00",
    "-",
    f"{peak_hour['Average_Hourly_Volume']:,.2f}"
)

print(
    "Highest average traffic day:",
    peak_day["Day"],
    "-",
    f"{peak_day['Average_Daily_Volume']:,.2f}"
)


# -------------------------------------------------------------
# Save current outputs
# -------------------------------------------------------------

output_folder = Path(
    r"C:\Users\LENOVO\Desktop\Project Urban\Data\EDA_Output\TIRTL"
)

output_folder.mkdir(
    parents=True,
    exist_ok=True
)


hourly_tirtl.to_csv(
    output_folder / "hourly_traffic_volume.csv",
    index=False
)

hourly_pattern_tirtl.to_csv(
    output_folder / "hourly_traffic_pattern.csv",
    index=False
)

daily_tirtl.to_csv(
    output_folder / "daily_traffic_volume.csv",
    index=False
)

day_pattern_tirtl.to_csv(
    output_folder / "day_of_week_traffic_pattern.csv",
    index=False
)

site_summary_tirtl.to_csv(
    output_folder / "site_traffic_summary.csv",
    index=False
)

monthly_volume_tirtl.to_csv(
    output_folder / "monthly_traffic_volume.csv",
    index=False
)

missing_summary_tirtl.to_csv(
    output_folder / "missing_values_summary.csv",
    index=False
)

vehicle_class_tirtl.to_csv(
    output_folder / "vehicle_class_volume.csv",
    index=False
)


print("\nOUTPUT FILES CREATED")

for file in sorted(
    output_folder.glob("*.csv")
):
    print("-", file.name)


print(
    "\nCurrent TIRTL analysis outputs "
    "saved successfully."
)

Aggregating file 1/215: TIRTLDATA_20260401.csv
Aggregating file 2/215: TIRTLDATA_20260402.csv
Aggregating file 3/215: TIRTLDATA_20260403.csv
Aggregating file 4/215: TIRTLDATA_20260404.csv
Aggregating file 5/215: TIRTLDATA_20260405.csv
Aggregating file 6/215: TIRTLDATA_20260406.csv
Aggregating file 7/215: TIRTLDATA_20260407.csv
Aggregating file 8/215: TIRTLDATA_20260408.csv
Aggregating file 9/215: TIRTLDATA_20260409.csv
Aggregating file 10/215: TIRTLDATA_20260410.csv
Aggregating file 11/215: TIRTLDATA_20260411.csv
Aggregating file 12/215: TIRTLDATA_20260412.csv
Aggregating file 13/215: TIRTLDATA_20260413.csv
Aggregating file 14/215: TIRTLDATA_20260414.csv
Aggregating file 15/215: TIRTLDATA_20260415.csv
Aggregating file 16/215: TIRTLDATA_20260416.csv
Aggregating file 17/215: TIRTLDATA_20260417.csv
Aggregating file 18/215: TIRTLDATA_20260418.csv
Aggregating file 19/215: TIRTLDATA_20260419.csv
Aggregating file 20/215: TIRTLDATA_20260420.csv
Aggregating file 21/215: TIRTLDATA_20260421.csv
Aggregating file 22/215: TIRTLDATA_20260422.csv
Aggregating file 23/215: TIRTLDATA_20260423.csv
Aggregating file 24/215: TIRTLDATA_20260424.csv
Aggregating file 25/215: TIRTLDATA_20260425.csv
Aggregating file 26/215: TIRTLDATA_20260426.csv
Aggregating file 27/215: TIRTLDATA_20260427.csv
Aggregating file 28/215: TIRTLDATA_20260428.csv
Aggregating file 29/215: TIRTLDATA_20260429.csv
Aggregating file 30/215: TIRTLDATA_20260430.csv
Aggregating file 31/215: TIRTLDATA_20260801.csv
Aggregating file 32/215: TIRTLDATA_20260802.csv
Aggregating file 33/215: TIRTLDATA_20260803.csv
Aggregating file 34/215: TIRTLDATA_20260804.csv
Aggregating file 35/215: TIRTLDATA_20260805.csv
Aggregating file 36/215: TIRTLDATA_20260201.csv
Aggregating file 37/215: TIRTLDATA_20260202.csv
Aggregating file 38/215: TIRTLDATA_20260203.csv
Aggregating file 39/215: TIRTLDATA_20260204.csv
Aggregating file 40/215: TIRTLDATA_20260205.csv
Aggregating file 41/215: TIRTLDATA_20260206.csv
Aggregating file 42/215: TIRTLDATA_20260207.csv
Aggregating file 43/215: TIRTLDATA_20260208.csv
Aggregating file 44/215: TIRTLDATA_20260209.csv
Aggregating file 45/215: TIRTLDATA_20260210.csv
Aggregating file 46/215: TIRTLDATA_20260211.csv
Aggregating file 47/215: TIRTLDATA_20260212.csv
Aggregating file 48/215: TIRTLDATA_20260213.csv
Aggregating file 49/215: TIRTLDATA_20260214.csv
Aggregating file 50/215: TIRTLDATA_20260215.csv
Aggregating file 51/215: TIRTLDATA_20260216.csv
Aggregating file 52/215: TIRTLDATA_20260217.csv
Aggregating file 53/215: TIRTLDATA_20260218.csv
Aggregating file 54/215: TIRTLDATA_20260219.csv
Aggregating file 55/215: TIRTLDATA_20260220.csv
Aggregating file 56/215: TIRTLDATA_20260221.csv
Aggregating file 57/215: TIRTLDATA_20260222.csv
Aggregating file 58/215: TIRTLDATA_20260223.csv
Aggregating file 59/215: TIRTLDATA_20260224.csv
Aggregating file 60/215: TIRTLDATA_20260225.csv
Aggregating file 61/215: TIRTLDATA_20260226.csv
Aggregating file 62/215: TIRTLDATA_20260227.csv
Aggregating file 63/215: TIRTLDATA_20260228.csv
Aggregating file 64/215: TIRTLDATA_20260101.csv
Aggregating file 65/215: TIRTLDATA_20260102.csv
Aggregating file 66/215: TIRTLDATA_20260103.csv
Aggregating file 67/215: TIRTLDATA_20260104.csv
Aggregating file 68/215: TIRTLDATA_20260105.csv
Aggregating file 69/215: TIRTLDATA_20260106.csv
Aggregating file 70/215: TIRTLDATA_20260107.csv
Aggregating file 71/215: TIRTLDATA_20260108.csv
Aggregating file 72/215: TIRTLDATA_20260109.csv
Aggregating file 73/215: TIRTLDATA_20260110.csv
Aggregating file 74/215: TIRTLDATA_20260111.csv
Aggregating file 75/215: TIRTLDATA_20260112.csv
Aggregating file 76/215: TIRTLDATA_20260113.csv
Aggregating file 77/215: TIRTLDATA_20260114.csv
Aggregating file 78/215: TIRTLDATA_20260115.csv
Aggregating file 79/215: TIRTLDATA_20260116.csv
Aggregating file 80/215: TIRTLDATA_20260117.csv
Aggregating file 81/215: TIRTLDATA_20260118.csv
Aggregating file 82/215: TIRTLDATA_20260119.csv
Aggregating file 83/215: TIRTLDATA_20260120.csv
Aggregating file 84/215: TIRTLDATA_20260121.csv
Aggregating file 85/215: TIRTLDATA_20260122.csv
Aggregating file 86/215: TIRTLDATA_20260123.csv
Aggregating file 87/215: TIRTLDATA_20260124.csv
Aggregating file 88/215: TIRTLDATA_20260125.csv
Aggregating file 89/215: TIRTLDATA_20260126.csv
Aggregating file 90/215: TIRTLDATA_20260127.csv
Aggregating file 91/215: TIRTLDATA_20260128.csv
Aggregating file 92/215: TIRTLDATA_20260129.csv
Aggregating file 93/215: TIRTLDATA_20260130.csv
Aggregating file 94/215: TIRTLDATA_20260131.csv
Aggregating file 95/215: TIRTLDATA_20260701.csv
Aggregating file 96/215: TIRTLDATA_20260702.csv
Aggregating file 97/215: TIRTLDATA_20260703.csv
Aggregating file 98/215: TIRTLDATA_20260704.csv
Aggregating file 99/215: TIRTLDATA_20260705.csv
Aggregating file 100/215: TIRTLDATA_20260706.csv
Aggregating file 101/215: TIRTLDATA_20260707.csv
Aggregating file 102/215: TIRTLDATA_20260708.csv
Aggregating file 103/215: TIRTLDATA_20260709.csv
Aggregating file 104/215: TIRTLDATA_20260710.csv
Aggregating file 105/215: TIRTLDATA_20260711.csv
Aggregating file 106/215: TIRTLDATA_20260712.csv
Aggregating file 107/215: TIRTLDATA_20260713.csv
Aggregating file 108/215: TIRTLDATA_20260714.csv
Aggregating file 109/215: TIRTLDATA_20260715.csv
Aggregating file 110/215: TIRTLDATA_20260716.csv
Aggregating file 111/215: TIRTLDATA_20260717.csv
Aggregating file 112/215: TIRTLDATA_20260718.csv
Aggregating file 113/215: TIRTLDATA_20260719.csv
Aggregating file 114/215: TIRTLDATA_20260720.csv
Aggregating file 115/215: TIRTLDATA_20260721.csv
Aggregating file 116/215: TIRTLDATA_20260722.csv
Aggregating file 117/215: TIRTLDATA_20260723.csv
Aggregating file 118/215: TIRTLDATA_20260724.csv
Aggregating file 119/215: TIRTLDATA_20260725.csv
Aggregating file 120/215: TIRTLDATA_20260726.csv
Aggregating file 121/215: TIRTLDATA_20260727.csv
Aggregating file 122/215: TIRTLDATA_20260728.csv
Aggregating file 123/215: TIRTLDATA_20260729.csv
Aggregating file 124/215: TIRTLDATA_20260601.csv
Aggregating file 125/215: TIRTLDATA_20260602.csv
Aggregating file 126/215: TIRTLDATA_20260603.csv
Aggregating file 127/215: TIRTLDATA_20260604.csv
Aggregating file 128/215: TIRTLDATA_20260605.csv
Aggregating file 129/215: TIRTLDATA_20260606.csv
Aggregating file 130/215: TIRTLDATA_20260607.csv
Aggregating file 131/215: TIRTLDATA_20260608.csv
Aggregating file 132/215: TIRTLDATA_20260609.csv
Aggregating file 133/215: TIRTLDATA_20260610.csv
Aggregating file 134/215: TIRTLDATA_20260611.csv
Aggregating file 135/215: TIRTLDATA_20260612.csv
Aggregating file 136/215: TIRTLDATA_20260613.csv
Aggregating file 137/215: TIRTLDATA_20260614.csv
Aggregating file 138/215: TIRTLDATA_20260615.csv
Aggregating file 139/215: TIRTLDATA_20260616.csv
Aggregating file 140/215: TIRTLDATA_20260617.csv
Aggregating file 141/215: TIRTLDATA_20260618.csv
Aggregating file 142/215: TIRTLDATA_20260619.csv
Aggregating file 143/215: TIRTLDATA_20260620.csv
Aggregating file 144/215: TIRTLDATA_20260621.csv
Aggregating file 145/215: TIRTLDATA_20260622.csv
Aggregating file 146/215: TIRTLDATA_20260623.csv
Aggregating file 147/215: TIRTLDATA_20260624.csv
Aggregating file 148/215: TIRTLDATA_20260625.csv
Aggregating file 149/215: TIRTLDATA_20260626.csv
Aggregating file 150/215: TIRTLDATA_20260627.csv
Aggregating file 151/215: TIRTLDATA_20260628.csv
Aggregating file 152/215: TIRTLDATA_20260629.csv
Aggregating file 153/215: TIRTLDATA_20260630.csv
Aggregating file 154/215: TIRTLDATA_20260301.csv
Aggregating file 155/215: TIRTLDATA_20260302.csv
Aggregating file 156/215: TIRTLDATA_20260303.csv
Aggregating file 157/215: TIRTLDATA_20260304.csv
Aggregating file 158/215: TIRTLDATA_20260305.csv
Aggregating file 159/215: TIRTLDATA_20260306.csv
Aggregating file 160/215: TIRTLDATA_20260307.csv
Aggregating file 161/215: TIRTLDATA_20260308.csv
Aggregating file 162/215: TIRTLDATA_20260309.csv
Aggregating file 163/215: TIRTLDATA_20260310.csv
Aggregating file 164/215: TIRTLDATA_20260311.csv
Aggregating file 165/215: TIRTLDATA_20260312.csv
Aggregating file 166/215: TIRTLDATA_20260313.csv
Aggregating file 167/215: TIRTLDATA_20260314.csv
Aggregating file 168/215: TIRTLDATA_20260315.csv
Aggregating file 169/215: TIRTLDATA_20260316.csv
Aggregating file 170/215: TIRTLDATA_20260317.csv
Aggregating file 171/215: TIRTLDATA_20260318.csv
Aggregating file 172/215: TIRTLDATA_20260319.csv
Aggregating file 173/215: TIRTLDATA_20260320.csv
Aggregating file 174/215: TIRTLDATA_20260321.csv
Aggregating file 175/215: TIRTLDATA_20260322.csv
Aggregating file 176/215: TIRTLDATA_20260323.csv
Aggregating file 177/215: TIRTLDATA_20260324.csv
Aggregating file 178/215: TIRTLDATA_20260325.csv
Aggregating file 179/215: TIRTLDATA_20260326.csv
Aggregating file 180/215: TIRTLDATA_20260327.csv
Aggregating file 181/215: TIRTLDATA_20260328.csv
Aggregating file 182/215: TIRTLDATA_20260329.csv
Aggregating file 183/215: TIRTLDATA_20260330.csv
Aggregating file 184/215: TIRTLDATA_20260331.csv
Aggregating file 185/215: TIRTLDATA_20260501.csv
Aggregating file 186/215: TIRTLDATA_20260502.csv
Aggregating file 187/215: TIRTLDATA_20260503.csv
Aggregating file 188/215: TIRTLDATA_20260504.csv
Aggregating file 189/215: TIRTLDATA_20260505.csv
Aggregating file 190/215: TIRTLDATA_20260506.csv
Aggregating file 191/215: TIRTLDATA_20260507.csv
Aggregating file 192/215: TIRTLDATA_20260508.csv
Aggregating file 193/215: TIRTLDATA_20260509.csv
Aggregating file 194/215: TIRTLDATA_20260510.csv
Aggregating file 195/215: TIRTLDATA_20260511.csv
Aggregating file 196/215: TIRTLDATA_20260512.csv
Aggregating file 197/215: TIRTLDATA_20260513.csv
Aggregating file 198/215: TIRTLDATA_20260514.csv
Aggregating file 199/215: TIRTLDATA_20260515.csv
Aggregating file 200/215: TIRTLDATA_20260516.csv
Aggregating file 201/215: TIRTLDATA_20260517.csv
Aggregating file 202/215: TIRTLDATA_20260518.csv
Aggregating file 203/215: TIRTLDATA_20260519.csv
Aggregating file 204/215: TIRTLDATA_20260520.csv
Aggregating file 205/215: TIRTLDATA_20260521.csv
Aggregating file 206/215: TIRTLDATA_20260522.csv
Aggregating file 207/215: TIRTLDATA_20260523.csv
Aggregating file 208/215: TIRTLDATA_20260524.csv
Aggregating file 209/215: TIRTLDATA_20260525.csv
Aggregating file 210/215: TIRTLDATA_20260526.csv
Aggregating file 211/215: TIRTLDATA_20260527.csv
Aggregating file 212/215: TIRTLDATA_20260528.csv
Aggregating file 213/215: TIRTLDATA_20260529.csv
Aggregating file 214/215: TIRTLDATA_20260530.csv
Aggregating file 215/215: TIRTLDATA_20260531.csv

======================================================================
CURRENT TIRTL TRAFFIC ANALYSIS
======================================================================

Rows processed: 211,284,853
Hourly periods created: 5,160
Days represented: 215

HOURLY TRAFFIC PATTERN

    Hour_of_Day  Total_Volume  Number_of_Hours  Average_Hourly_Volume
0             0      35762818              215              166338.69
1             1      21787382              215              101336.66
2             2      16438076              215               76456.17
3             3      19293269              215               89736.13
4             4      43248134              215              201154.11
5             5     120748542              215              561621.13
6             6     171052145              215              795591.37
7             7     193273147              215              898944.87
8             8     203646831              215              947194.56
9             9     203019042              215              944274.61
10           10     205171260              215              954284.93
11           11     213826825              215              994543.37
12           12     220272410              215             1024522.84
13           13     226212619              215             1052151.72
14           14     246641400              215             1147169.30
15           15     255358853              215             1187715.60
16           16     255572141              215             1188707.63
17           17     250905512              215             1167002.38
18           18     201331910              215              936427.49
19           19     142196387              215              661378.54
20           20     117537370              215              546685.44
21           21     104540406              215              486234.45
22           22      84154749              215              391417.44
23           23      59081461              215              274797.49

DAY-OF-WEEK TRAFFIC PATTERN

         Day  Total_Volume  Number_of_Days  Average_Daily_Volume
0     Monday     506559230              31           16340620.32
1    Tuesday     527546089              31           17017615.77
2  Wednesday     540957720              31           17450249.03
3   Thursday     528934773              30           17631159.10
4     Friday     556423133              30           18547437.77
5   Saturday     504861916              31           16285868.26
6     Sunday     445789828              31           14380317.03

TOP 10 SITES BY RECORDED TRAFFIC VOLUME

   Site  Total_Volume
0    26      22384495
1    24      22301230
2   167      22153668
3   173      22086659
4   580      22049437
5    16      21131815
6   166      21080859
7    25      21020677
8    18      20916322
9   179      20713598

CURRENT TRAFFIC PATTERNS
Highest average traffic hour: 16:00 - 1,188,707.63
Highest average traffic day: Friday - 18,547,437.77

OUTPUT FILES CREATED
- daily_traffic_volume.csv
- day_of_week_traffic_pattern.csv
- hourly_traffic_pattern.csv
- hourly_traffic_volume.csv
- missing_values_summary.csv
- monthly_traffic_volume.csv
- site_traffic_summary.csv
- vehicle_class_volume.csv

Current TIRTL analysis outputs saved successfully.